#!/bin/bash

DEPENDENCIES=(
  coreutils
  systemd
  tmux
  vim-minimal
)

#copy-to-rootfs
cpfs() {
  local target=rootfs/${2#/}
  [[ ! -a $1 ]] && {
    echo "source does not exist: $1"
    exit 1
  }
  [[ -f $target ]] && {
    echo "target exists but is not a directory: $2"
    exit 1
  }
  [[ ! -a $target ]] && {
    mkdir -p $target
  }
  cp $1 $target/${3:-$1}
}

prepare_rootfs() {
  cpfs systemux-tmux@.service /etc/systemd/system
  cpfs systemux.service /etc/systemd/system
  cpfs systemux.target /etc/systemd/system
  cpfs hello /bin
  cpfs tmux.conf /usr/share/systemux
  cpfs systemux-generator /usr/lib/systemd/system-generators
  cpfs 10-kernel-quiet.conf /etc/sysctl.d
  cpfs rescue_passwordless.conf /etc/systemd/system/rescue.service.d override.conf
  systemctl --root rootfs set-default systemux.target
}

check_root() {
  [[ $EUID -ne 0 ]] && {
    echo "run as root user"
    exit 1
  }
}

main_method() {
  check_root
  local OPTIND OPTARG OPTION
  local full=false
  local img=false
  while getopts "fi" OPTION; do
    case "${OPTION}" in
    f)
      full=true
      ;;
    i)
      img=true
      ;;
    esac
  done
  $full || [[ ! -a rootfs ]] && {
    rm -rf rootfs
    mkdir -p rootfs
    dnf -y --use-host-config --installroot $(realpath rootfs) install ${DEPENDENCIES[@]}
  }
  prepare_rootfs
  $img || [[ ! -a systemux.img ]] && {
    rm -f systemux.img
    mksquashfs rootfs systemux.img
  }
}

return 2> /dev/null || main_method $@
