#!/bin/bash

[[ $EUID -ne 0 ]] && {
  echo "[ERROR] run as root user"
  return 1
}

[[ ! -a live.img ]] && {
  echo "[ERROR] live.img not found, see README"
  exit 1
}

curl --silent --fail -m2 -I --noproxy '*' http://$(hostname -I | xargs):3000/systemux.img || {
  echo "[ERROR] start http server first, see README"
  exit 1
}

#Press Ctrl-a, then x to kill container.
exec qemu-system-x86_64 \
  -kernel /boot/vmlinuz-$(uname -r) \
  -initrd live.img \
  -append "panic=60 console=ttyS0 root=live:http://$(hostname -I | xargs):3000/systemux.img" \
  -netdev user,id=net0 \
  -device rtl8139,netdev=net0 \
  -m size=2048 \
  -nographic
